services:
  - type: web
    runtime: go
    name: digital-stamp-api
    region: singapore
    plan: free
    buildCommand: go build -o app ./cmd/api
    startCommand: ./app
    healthCheckPath: /api/health
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
